


trian:
	@echo "Running the training script"

evaluate:
	@echo "Running the evaluation script"

simple_run:
	python train.py --config config.json --data ./data/generated_data/

pressure_run:
	python train.py --config config.json --data ./data/generated_data/


clean:
	rm -rf ./checkpoints
	rm -rf ./log.txt
